### ISSUE TITLE
components の export const ... を　const ... で　あとで export default にすればよいかも

### ISSUE THREAD

**Issue by moto-sbt** [moto-sbt/nextjs-blog#38]
＃参考
![image](https://user-images.githubusercontent.com/74887303/183115786-00110f4e-4e60-48d9-a5fa-6348daabd515.png)

**Comment by moto-sbt** [comment]
なんかwarningでてたのであとで調べる

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <ul>. See https://reactjs.org/link/warning-keys for more information.
    at PostItem (webpack-internal:///./components/molecules/PostItem.tsx:13:21)
    at PostItems (webpack-internal:///./components/organisms/PostItems.tsx:10:22)
    at section
    at main
    at div
    at Layout (webpack-internal:///./components/layout.tsx:21:19)
    at Home (webpack-internal:///./pages/index.tsx:29:17)
    at App (webpack-internal:///./pages/_app.tsx:11:16)
    at StyleRegistry (/Users/user/work/nextjs-tutorial/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/user/work/nextjs-tutorial/node_modules/next/dist/server/render.js:404:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/user/work/nextjs-tutorial/node_modules/next/dist/server/render.js:433:57)
    at div
    at Body (/Users/user/work/nextjs-tutorial/node_modules/next/dist/server/render.js:690:21)
```

**Comment by moto-sbt** [comment]
この形で統一する  


```tsx
type Props = {
    xxx: xxx
}

const Xxx = ({ xxx } : Props ) => {
    return (
        <>

        ...

        </>
    )
}

export default Xxx
```
